# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily pipeline 

on:
  workflow_dispatch: {}
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Feel free to change this cron schedule
    # Currently its scheduled for 6:25 am, Sun-Thurs
    - cron:  '25 6 * * 0-4'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
    - name: Generate Digest 
      run: |
        python src/action.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
